language: generic
sudo: required

services:
  - docker
before_install:
  - docker build -t kbu715/react-test-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kbu715/react-test-app npm run test
# script:
#   - echo "skipping tests"

after_success:
  - docker build -t kbu715/docker-frontend ./client
  - docker build -t kbu715/docker-backend ./server
  - docker build -t kbu715/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push kbu715/docker-frontend
  - docker push kbu715/docker-backend
  - docker push kbu715/docker-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "docker-movie"
#   env: "DockerMovie-env"
#   bucket_name: elasticbeanstalk-ap-northeast-2-128529754877
#   bucket_path: "docker-movie"
#   on:
#     branch: master

#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
